name: build-oval-files
on: [push]
jobs:
  build-xml-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: sudo apt install -y python3-lxml jq
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: | 
          python -m pip install -r scripts/requirements.txt
          mkdir ./output-files
          echo "Update Web Indexes"
          python ./scripts/web_update_indexes.py > /dev/null
          echo "Get Platform Stats"
          python ./scripts/web_get_repository_stats.py --platform > platforms.json
          for platform in $(cat platforms.json | jq '.RESULTS.platforms | keys'); do
            echo "$platform"
            echo "Build OVAL Definitions Files for $platform"
            for directory in $(ls ./repository/definitions); do
              if [ -d "$directory" ]; then
                  echo "python ./scripts/build_oval_definitions_file.py --outfile=./output-files/5.10/$directory/$platform.xml --max_schema_version=5.10 --platform=$platform --class=$directory";
                  echo "python ./scripts/build_oval_definitions_file.py --outfile=./output-file/5.11.1/$directory/$platform.xml --max_schema_version=5.11.1 --platform=$platform --class=$directory";
                  echo "python ./scripts/build_oval_definitions_file.py --outfile=./output-files/5.11.2/$directory/$platform.xml --max_schema_version=5.11.2 --platform=$platform --class=$directory";
              fi
            done
          done
          
          cd ../../
          echo "Build All OVAL Definitions File"
          # python ./scripts/build_oval_definitions_file.py --all_definitions --outfile ./output-files/oval.xml
          ls -lah output-files
